services:
  postgres:
    image: postgres:16-alpine
    container_name: proyecto-postgres
    restart: unless-stopped
    ports:
      - "5431:5431"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=proyecto_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proyecto-de-grado-api
    restart: unless-stopped
    ports:
      - "4001:4001"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=4001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=proyecto_db
    networks:
      - backend-network



networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local