version: '3.8'

services:
  api:
    build: .
    container_name: proyecto-de-grado-api
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-4000}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_DATABASE=${DB_DATABASE:-proyecto_db}
    command: npm run dev

  postgres:
    image: postgres:16-alpine
    container_name: proyecto-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_DATABASE:-proyecto_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: